#cloud-config
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCj/l0QGAt9cMmR+7MmKEGksEVIjni0RuamSQg2NdZr2LvJlOxSFl0fCrz1RQKj/MvdvNbmmCbiVPv5CTEnEeKnIStxArj9wpQ+YcydsX7rNWKRm05sIw1UoZAcrodmDOJlD4UZmOPus2RMy8G8alvz1xAW1FtpXpVwolUR52mgEau927OF0Vi6UPkdu+dFMI5ABVKniilLaqfFdXOUSCXaw47Y4jmshW9SQuMN3Z8CDvsIVQay63lTWO7PleoQ5mKIbDi+7AHC9C7wyjboPHKqwDlB6jcpHo6g5f8SNxsud7PyxVYxRHx2ayHXx14+vhU7flauoYXQqd0m2o74vi6nhb1pLpQqqMadAO97cIH99zOiteo83guJSC5FMfLa5665oP8G44rG7hUHOfxm0QiawW00Db88IF5ek2ScumFDFmVPrrDd1vxaw84p6xZAC1FMJJTkv+deMoVjmxshhebefgUyiP8biGuAYQQjpXsFtF8hwTgqKdUVc64TWIWvY9LO9+LjWmy+FIb6BO27kzF6+WGYSDSYEqo4ML+Nq5EQ4Kp0ttU4nkmQhW3SOhNrdD4bSdj1bVjwRzFqYrUGgdlmFkaiESin9Izi9XQatiq1TatGsBFhBNPnh+ULb4m5Q03XfpGCaxHB0zV662pRKDZsLT0V8SZ1JpkyoWRnrEC5kw== jbartels@gmail.com
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQZWm5o4AENkFKeKbXpgX6Fb7BEuNwhZA+pDoglbm+NMvjxWrog8cwpWdGQPSz7ntGHI+7BvUZS2lK6hOLPUvGhxvcBaqwZbBizTcNgzx1ZovJUGXeFYc4xixY+eihssPhVaT3JicH6JsI6jkRMaSkDp0d9CTU8MYFOZFZF90xo7XRfjOV64oQ7jme6r8cVPjxq5N56J2ljkfa4SwE2hc2s1Z7KlBSRU7OlNyJ8fJKQETVm9xMqGQcqm0DkxjCoFccdBAjdeAjJMq7+ALQU2kEVPvTfRy3g9p2SfRYX0d5z2ap+kN858xishFv4Bt5g5M0nn3LUNVLl+M5jwjro6upj/0y917U9hMNn+rNb1Urouk7h8nboRTMubIaSJHBqrC5wEM2YXbXmWRpGFR8YsAd2HhG3Kx5K8AiAUPLjLfJs6jp60MtqXpj/p4egRfbmr8qC18Wa4R6BmEbO7DMPG6COH6eSrNVbfXr3zS/WRD4beZj4wSwVQzNjvATyoLDnBArtmeITq/Q0L8IJHgrbdre53tlhpB+RUqubCyMNR+OkxNk7an7Dsr/KXzjWyD33KvKufkqQRLCXYhkWGJ6Q9NYhYVpdutTY1bFekF8hb+dfxWt1yU2PPehcdiVn0pz+7CQ0KI18Tq/CBjU8IY3paDE7blDtodNejIlE3Kxt6MHCQ== jbartels@gmail.com
mounts:
- - //10.10.101.4/Volume_1
  - /mnt/media/bnas1
  - cifs
  - username=guest,iocharset=utf8,_netdev
rancher:
  services:
    nginx-proxy:
      image: jwilder/nginx-proxy:latest
      restart: unless-stopped
      ports:
      - "80:80"
      - "443:443"
      volumes:
      - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:ro'
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    letsencrypt-nginx-proxy-companion:
      image: jrcs/letsencrypt-nginx-proxy-companion:latest
      restart: unless-stopped
      volumes_from:
      - nginx-proxy
      volumes:
      - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    plex-stats:
      image: linuxserver/tautulli:latest
      restart: unless-stopped
      environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=stats.joshly.com
      - LETSENCRYPT_TEST=false
      - LETSENCRYPT_HOST=stats.joshly.com
      - LETSENCRYPT_EMAIL=jbartels@gmail.com
      volumes:
      - '/home/docker/tautulli:/config'
      - '/var/log/plexpy:/logs:ro'
      - '/home/docker/certs:/certs'
    portainer:
      image: portainer/portainer
      restart: unless-stopped
      command: --templates http://templates/templates.json
      volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/home/docker/portainer/data:/data'
      ports:
        - "9000:9000"
      environment:
        - TZ=America/New_York
        - VIRTUAL_PORT=9000
        - VIRTUAL_HOST=portainer.joshly.com
        - LETSENCRYPT_TEST=false
        - LETSENCRYPT_HOST=portainer.joshly.com
        - LETSENCRYPT_EMAIL=jbartels@gmail.com
