#cloud-config
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCj/l0QGAt9cMmR+7MmKEGksEVIjni0RuamSQg2NdZr2LvJlOxSFl0fCrz1RQKj/MvdvNbmmCbiVPv5CTEnEeKnIStxArj9wpQ+YcydsX7rNWKRm05sIw1UoZAcrodmDOJlD4UZmOPus2RMy8G8alvz1xAW1FtpXpVwolUR52mgEau927OF0Vi6UPkdu+dFMI5ABVKniilLaqfFdXOUSCXaw47Y4jmshW9SQuMN3Z8CDvsIVQay63lTWO7PleoQ5mKIbDi+7AHC9C7wyjboPHKqwDlB6jcpHo6g5f8SNxsud7PyxVYxRHx2ayHXx14+vhU7flauoYXQqd0m2o74vi6nhb1pLpQqqMadAO97cIH99zOiteo83guJSC5FMfLa5665oP8G44rG7hUHOfxm0QiawW00Db88IF5ek2ScumFDFmVPrrDd1vxaw84p6xZAC1FMJJTkv+deMoVjmxshhebefgUyiP8biGuAYQQjpXsFtF8hwTgqKdUVc64TWIWvY9LO9+LjWmy+FIb6BO27kzF6+WGYSDSYEqo4ML+Nq5EQ4Kp0ttU4nkmQhW3SOhNrdD4bSdj1bVjwRzFqYrUGgdlmFkaiESin9Izi9XQatiq1TatGsBFhBNPnh+ULb4m5Q03XfpGCaxHB0zV662pRKDZsLT0V8SZ1JpkyoWRnrEC5kw== jbartels@gmail.com
rancher:
  services:
    nginx-proxy:
      image: jwilder/nginx-proxy:latest
      restart: unless-stopped
      ports:
      - "80:80"
      - "443:443"
      volumes:
      - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:ro'
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    letsencrypt-nginx-proxy-companion:
      image: jrcs/letsencrypt-nginx-proxy-companion:latest
      restart: unless-stopped
      volumes_from:
      - nginx-proxy
      volumes:
      - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    plex-stats:
      image: linuxserver/tautulli:latest
      restart: unless-stopped
      environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=stats.joshly.com
      - LETSENCRYPT_TEST=false
      - LETSENCRYPT_HOST=stats.joshly.com
      - LETSENCRYPT_EMAIL=jbartels@gmail.com
      volumes:
      - ${USERDIR}/docker/tautulli:/config
      - /var/log/plexpy:/logs:ro
      - ${USERDIR}/docker/certs:/certs
    portainer:
      image: portainer/portainer
      restart: unless-stopped
      command: --templates http://templates/templates.json
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${USERDIR}/docker/portainer/data:/data
      ports:
        - "9000:9000"
      environment:
        - TZ=${TZ}
        - VIRTUAL_PORT=9000
        - VIRTUAL_HOST=movies2.joshly.com
        - LETSENCRYPT_TEST=false
        - LETSENCRYPT_HOST=movies2.joshly.com
        - LETSENCRYPT_EMAIL=jbartels@gmail.com